# Example configuration file for a project.

files:
  suffix: md
  root: /Users/dag/dev/pagery/example/
  post: post
  page: page
  resource: resources/
  target: /Users/dag/dev/pagery/pagery-out/
  resources: # Set up the CSS resources that needs a load order. Any resource listed will be given a random order.
    - location: pure-min.css
      loadOrder: 1
    - location: grids-responsive-min.css
      loadOrder: 2
    - location: blog.css
      loadOrder: 3

project:
  title: Pagery Static Blog
  path: http://localhost:8080
  info: This is a blog about a static blog generator named Pagery.
          Pagery is on github and other places.
  postlimit: 1 # Amount of posts to show on the frontpage

server:
  name: localhost
  host: localhost
  port: 8080