# Example configuration file for a project.

files:
  suffix: md
  root: /Users/dag/dev/pagery/example/
  post: post
  page: page

project:
  title: Pagery Static Blog
  path: http://localhost:8080
  info: This is a blog about a static blog generator named Pagery.
          Pagery is on github and other places.
  postlimit: 1 # Amount of posts to show on the frontpage

server:
  name: localhost
  host: localhost
  port: 8080